[package]
name = "rustracer-api"
version = "0.1.0"
edition = "2021"

[dependencies]
jpeg-encoder = "0.6.0"
tide = "0.14.0"
femme = "2.2.1"
async-std = { version = "1.6.0", features = ["attributes"] }
serde = { version = "1.0", features = ["derive"] }
rustracer-core = { path = "../rustracer-core" }